# Travis file
# See https://docs.travis-ci.com/user/languages/r/

language: R
sudo: false
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

addons:
  apt:
    packages:
      - libxml2-dev
